version: '3.4'

services: 
    webserver:
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/

    node_dev:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            target: node
        stdin_open: true
        ports:
            - 3000:3000
        volumes:
            - ./:/opt/app/
        entrypoint:
            - '/usr/local/bin/npm'
        command:
            - 'start'
